language: python
python:
  - 3.5
script:
  - cd $TRAVIS_BUILD_DIR/02 && make
  - cd $TRAVIS_BUILD_DIR/03 && make
addons:
  apt:
    packages:
      - mecab
      - libmecab-dev
      - python-mecab
notifications:
  webhooks: http://webhook.hakatashi.com/travis
