language: python
python:
  - 3.5
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mecab mecab-ipadic-utf8 libmecab-dev
  - mecab --version
  - mecab-config --version
script:
  - cd $TRAVIS_BUILD_DIR/02 && make
  - cd $TRAVIS_BUILD_DIR/03 && make
notifications:
  webhooks: http://webhook.hakatashi.com/travis
